export enum StdStatus {
  SUCCESS = 0,
  INVALID_ARGUMENT = 1,
  NOT_FOUND = 2,
  UNAUTHENTICATED = 3,
  PERMISSION_DENIED = 4,
  VALIDATION_FAILURE = 5,
  ALREADY_EXISTS = 6,
  INTERNAL_ERROR = 7,
}
